# Setup
title:               'Jayaprakash Sundararaj'
tagline:             ''
description:         ''
url:                 'https://www.jayaprakash.net'
baseurl:             ''
permalink:           pretty
show_downloads:      false

author:
  name:              Jayaprakash Sundararaj
  url:               'https://www.jayaprakash.net/'
  email:             'osjp463@gmail.com'
  picture:           'https://www.jayaprakash.net/images/jp.jpg'

# theme: jekyll-theme-hacker
remote_theme: pages-themes/slate@v0.2.0
#theme: jekyll-theme-slate

defaults:
  - values:
      seo_description_max_words: 200

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-sitemap
  - faraday-retry

seo_paginator_message: "%<current>s / %<total>s | "
